import os
from abc import ABC, abstractmethod


class PlatformAdapter(ABC):
    """
    平台适配器基类。
    任何新的 AI 工具平台只需要继承这个类，并实现以下两个方法。
    """

    @property
    @abstractmethod
    def platform_name(self) -> str:
        """平台名称，如 'cursor', 'claude', 'hermes'"""
        pass

    @abstractmethod
    def get_target_path(self, project_root: str, skill_name: str) -> str:
        """返回该平台期望的文件保存路径"""
        pass

    @abstractmethod
    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        """根据平台要求，组装最终的文件内容（如 Frontmatter, JSON 等）"""
        pass


class CursorAdapter(PlatformAdapter):
    @property
    def platform_name(self) -> str:
        return "cursor"

    def get_target_path(self, project_root: str, skill_name: str) -> str:
        # Cursor 通常保存在 .cursor/agents/ 或 .cursor/rules/
        return os.path.join(project_root, ".cursor", "agents", f"{skill_name}.md")

    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        warning = (
            "<!-- 🤖 GENERATED BY AGENT-SYNC. DO NOT EDIT DIRECTLY! -->\n" if add_warning else ""
        )
        frontmatter = ""
        if name or desc:
            frontmatter = f"---\n"
            if name:
                frontmatter += f"name: {name}\n"
            if desc:
                frontmatter += f"description: {desc}\n"
            frontmatter += f"---\n"

        if mode == "reference":
            return frontmatter + warning + f"Please refer to: {body.strip()}"
        return frontmatter + warning + body


class ClaudeAdapter(PlatformAdapter):
    @property
    def platform_name(self) -> str:
        return "claude"

    def get_target_path(self, project_root: str, skill_name: str) -> str:
        # Claude Code 通常保存在 .claude/skills/<name>/SKILL.md
        return os.path.join(project_root, ".claude", "skills", skill_name, "SKILL.md")

    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        # Claude 的格式可能与 Cursor 类似，也可能不同。这里使用独立的适配器逻辑
        warning = (
            "<!-- 🤖 GENERATED BY AGENT-SYNC. DO NOT EDIT DIRECTLY! -->\n" if add_warning else ""
        )
        frontmatter = ""
        if name or desc:
            frontmatter = f"---\n"
            if name:
                frontmatter += f"name: {name}\n"
            if desc:
                frontmatter += f"description: {desc}\n"
            frontmatter += f"---\n"

        if mode == "reference":
            return frontmatter + warning + f"Please refer to: {body.strip()}"
        return frontmatter + warning + body


# 注册表：所有支持的平台都在这里注册
ADAPTERS = {
    "cursor": CursorAdapter(),
    "claude": ClaudeAdapter(),
}


def get_adapter(platform_name: str) -> PlatformAdapter:
    if platform_name not in ADAPTERS:
        raise ValueError(f"Unsupported platform: {platform_name}")
    return ADAPTERS[platform_name]
