import os
import re
from abc import ABC, abstractmethod

AGENT_SYNC_MARKER = "<!-- 🤖 GENERATED BY AGENT-SYNC. DO NOT EDIT DIRECTLY! -->\n"


class PlatformAdapter(ABC):
    """
    平台适配器基类。
    任何新的 AI 工具平台只需要继承这个类，并实现以下方法。
    """

    @property
    @abstractmethod
    def platform_name(self) -> str:
        """平台名称，如 'cursor', 'claude', 'hermes'"""
        pass

    @abstractmethod
    def get_target_path(self, project_root: str, skill_name: str) -> str:
        """返回该平台期望的文件保存路径"""
        pass

    @abstractmethod
    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        """根据平台要求，组装最终的文件内容（如 Frontmatter, JSON 等）"""
        pass

    def is_managed(self, file_content: str) -> bool:
        """检查文件是否由 AgentSync 管理（用于防覆盖和孤儿清理）"""
        return AGENT_SYNC_MARKER.strip() in file_content

    @abstractmethod
    def extract_content(self, file_content: str) -> str:
        """逆向剥壳：从加壳的文件中提取纯净的 Markdown 正文（用于 push 反推）"""
        pass


class CursorAdapter(PlatformAdapter):
    @property
    def platform_name(self) -> str:
        return "cursor"

    def get_target_path(self, project_root: str, skill_name: str) -> str:
        # Cursor 通常保存在 .cursor/agents/ 或 .cursor/rules/
        return os.path.join(project_root, ".cursor", "agents", f"{skill_name}.md")

    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        warning = AGENT_SYNC_MARKER if add_warning else ""
        frontmatter = ""
        if name or desc:
            frontmatter = f"---\n"
            if name:
                frontmatter += f"name: {name}\n"
            if desc:
                frontmatter += f"description: {desc}\n"
            frontmatter += f"---\n"

        if mode == "reference":
            return frontmatter + warning + f"Please refer to: {body.strip()}"
        return frontmatter + warning + body

    def extract_content(self, file_content: str) -> str:
        # 移除 marker
        content = file_content.replace(AGENT_SYNC_MARKER, "")
        # 移除 frontmatter
        content = re.sub(r"^---\n.*?\n---\n", "", content, flags=re.DOTALL)
        # 移除 reference 模式的前缀
        content = re.sub(r"^Please refer to: ", "", content)
        return content.strip()


class ClaudeAdapter(PlatformAdapter):
    @property
    def platform_name(self) -> str:
        return "claude"

    def get_target_path(self, project_root: str, skill_name: str) -> str:
        # Claude Code 通常保存在 .claude/skills/<name>/SKILL.md
        return os.path.join(project_root, ".claude", "skills", skill_name, "SKILL.md")

    def format_content(self, name: str, desc: str, body: str, mode: str, add_warning: bool) -> str:
        warning = AGENT_SYNC_MARKER if add_warning else ""
        frontmatter = ""
        if name or desc:
            frontmatter = f"---\n"
            if name:
                frontmatter += f"name: {name}\n"
            if desc:
                frontmatter += f"description: {desc}\n"
            frontmatter += f"---\n"

        if mode == "reference":
            return frontmatter + warning + f"Please refer to: {body.strip()}"
        return frontmatter + warning + body

    def extract_content(self, file_content: str) -> str:
        content = file_content.replace(AGENT_SYNC_MARKER, "")
        content = re.sub(r"^---\n.*?\n---\n", "", content, flags=re.DOTALL)
        content = re.sub(r"^Please refer to: ", "", content)
        return content.strip()


# 注册表：所有支持的平台都在这里注册
ADAPTERS = {
    "cursor": CursorAdapter(),
    "claude": ClaudeAdapter(),
}


def get_adapter(platform_name: str) -> PlatformAdapter:
    if platform_name not in ADAPTERS:
        raise ValueError(f"Unsupported platform: {platform_name}")
    return ADAPTERS[platform_name]
