import os
import logging
from typing import List
from agent_sync.adapters import get_adapter, ADAPTERS

logger = logging.getLogger(__name__)


def safe_write(filepath: str, content: str, force: bool = False):
    """
    安全写入：防覆盖保护 (Overwrite Protection)
    """
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            existing_content = f.read()
        # 如果文件存在且没有 AgentSync 标记，说明是用户私有文件
        if "GENERATED BY AGENT-SYNC" not in existing_content and not force:
            raise FileExistsError(
                f"文件 {filepath} 已存在且非 AgentSync 管理。\n"
                f"为防止数据丢失，已跳过覆盖。请使用 --force 强制覆盖。"
            )

    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w") as f:
        f.write(content)
    logger.info(f"Successfully wrote to {filepath}")


def prune_orphans(project_root: str, active_skill_names: List[str]):
    """
    清理孤儿文件 (Pruning / Cleanup)：
    删除由 AgentSync 管理但不在当前配置中的文件。
    """
    for platform_name, adapter in ADAPTERS.items():
        # 获取该平台的根目录，例如 .cursor/agents 或 .claude/skills
        # 这里用一个 dummy skill name 来推断目录
        dummy_path = adapter.get_target_path(project_root, "dummy_for_prune")
        target_dir = os.path.dirname(dummy_path)

        # Claude 的路径是 .claude/skills/<name>/SKILL.md，所以目录结构不同
        if platform_name == "claude":
            target_dir = os.path.dirname(target_dir)  # 退到 .claude/skills

        if not os.path.exists(target_dir):
            continue

        # 遍历目录查找孤儿
        if platform_name == "cursor":
            for filename in os.listdir(target_dir):
                if not filename.endswith(".md"):
                    continue
                skill_name = filename[:-3]
                filepath = os.path.join(target_dir, filename)
                _check_and_remove(filepath, skill_name, active_skill_names, adapter)
        elif platform_name == "claude":
            for skill_name in os.listdir(target_dir):
                filepath = os.path.join(target_dir, skill_name, "SKILL.md")
                if os.path.exists(filepath):
                    _check_and_remove(filepath, skill_name, active_skill_names, adapter)


def _check_and_remove(filepath: str, skill_name: str, active_skill_names: List[str], adapter):
    with open(filepath, "r") as f:
        content = f.read()
    # 只有带有 AgentSync 标记的文件，并且不在活跃列表中的，才会被清理
    if adapter.is_managed(content) and skill_name not in active_skill_names:
        os.remove(filepath)
        print(f"已清理孤儿文件: {filepath}")
