import re


def strip_frontmatter(content: str) -> str:
    return re.sub(r"^---\n.*?\n---\n", "", content, flags=re.DOTALL).strip()


def generate_cursor_agent(name: str, desc: str, body: str, mode: str = "inline") -> str:
    warning = "<!-- 🤖 GENERATED BY AGENT-SYNC. DO NOT EDIT DIRECTLY! -->\n"
    frontmatter = f"---\nname: {name}\ndescription: {desc}\n---\n"

    if mode == "reference":
        return frontmatter + warning + f"Please refer to: {body.strip()}"

    return frontmatter + warning + body
