import re


def strip_frontmatter(content: str, enable: bool = True) -> str:
    """
    剥离 Markdown 的 Frontmatter 头部信息。
    如果 enable 为 False，则原样返回。
    """
    if not enable:
        return content.strip()
    return re.sub(r"^---\n.*?\n---\n", "", content, flags=re.DOTALL).strip()


def generate_cursor_agent(
    name: str, desc: str, body: str, mode: str = "inline", add_warning: bool = True
) -> str:
    """
    生成 Cursor 格式的 Agent 文件。
    可以通过 add_warning 控制是否添加防篡改注释。
    """
    warning = "<!-- 🤖 GENERATED BY AGENT-SYNC. DO NOT EDIT DIRECTLY! -->\n" if add_warning else ""

    # 如果 body 已经包含了 frontmatter 并且我们选择不剥离它，这里需要注意避免双重 frontmatter
    # 但通常调用方会决定是否传入干净的 body。这里我们只负责组装。
    # 为了更灵活，如果 name 和 desc 为空，我们可以选择不生成新的 frontmatter
    frontmatter = ""
    if name or desc:
        frontmatter = f"---\n"
        if name:
            frontmatter += f"name: {name}\n"
        if desc:
            frontmatter += f"description: {desc}\n"
        frontmatter += f"---\n"

    if mode == "reference":
        return frontmatter + warning + f"Please refer to: {body.strip()}"

    return frontmatter + warning + body
