"""initial schema: experiences, feedbacks, api_keys with pgvector

Revision ID: 06387edfbe6e
Revises: 
Create Date: 2026-02-10 09:21:29.888969

"""
from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06387edfbe6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('programming_language', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('code_snippets', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feedback_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create vector similarity index (IVFFlat with cosine distance)
    op.execute("""
        CREATE INDEX idx_exp_embedding ON experiences
        USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)
    """)
    # Create GIN index for tag array search
    op.execute("CREATE INDEX idx_exp_tags ON experiences USING GIN (tags)")
    # Create index for recent queries
    op.execute("CREATE INDEX idx_exp_created_at ON experiences (created_at DESC)")
    # Create index for creator lookup
    op.execute("CREATE INDEX idx_exp_created_by ON experiences (created_by)")
    # Create index for feedback lookup
    op.execute("CREATE INDEX idx_feedback_exp_id ON experience_feedbacks (experience_id)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_feedbacks')
    op.drop_table('experiences')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
