from agent_sync.parser import strip_frontmatter, generate_cursor_agent


def test_strip_frontmatter():
    content = "---\nname: test\n---\nBody text"
    assert strip_frontmatter(content).strip() == "Body text"


def test_generate_cursor_agent():
    body = "Body text"
    result = generate_cursor_agent("reviewer", "desc", body)
    assert "name: reviewer" in result
    assert "GENERATED BY AGENT-SYNC" in result
    assert "Body text" in result
