from agent_sync.parser import strip_frontmatter, generate_cursor_agent


def test_strip_frontmatter():
    content = "---\nname: test\n---\nBody text"
    assert strip_frontmatter(content).strip() == "Body text"

    # Test when stripping is disabled
    assert strip_frontmatter(content, enable=False).strip() == content.strip()


def test_generate_cursor_agent():
    body = "Body text"
    result = generate_cursor_agent("reviewer", "desc", body)
    assert "name: reviewer" in result
    assert "GENERATED BY AGENT-SYNC" in result
    assert "Body text" in result

    # Test without warning
    result_no_warning = generate_cursor_agent("reviewer", "desc", body, add_warning=False)
    assert "GENERATED BY AGENT-SYNC" not in result_no_warning
    assert "name: reviewer" in result_no_warning

    # Test without adding new frontmatter (when name and desc are empty)
    result_no_frontmatter = generate_cursor_agent("", "", body, add_warning=False)
    assert "---\n" not in result_no_frontmatter
    assert body in result_no_frontmatter
